class CheckingAccount():...
class Bond():...
class SavingAccount():...
class Security(Bond):...
class Stock(Security):...


class BankAccaunt(SavingAccount, CheckingAccount):...

class InterestBearingItem(BankAccaunt):...
class RealEstete():...

class Asset(BankAccaunt,RealEstete,Security):...
class InsurableItem(BankAccaunt,RealEstete):...

print(InsurableItem.mro())

